### ISSUE TITLE
Not compatible with bootstrap 4

### ISSUE THREAD

**Issue by Tes3awy** [mladenplavsic/bootstrap-navbar-sidebar#1]
It's not fully compatible with Bootstrap 4.beta.2; _the latest version at the moment of writing this issue._ The problem is that navbar-expand-{sm | md | lg | xl} is added and some other classes have been changed. All changes can be found [here](https://getbootstrap.com/docs/4.0/migration/)

**Comment by mladenplavsic** [comment]
Hi there!
There is a WIP branch covering this issue here https://github.com/mladenplavsic/bootstrap-navbar-sidebar/tree/bootstrap-v4
Please feel free to use it, and give feedback or contribute if something is wrong.
Cheers!
