### ISSUE TITLE
Useless class selector in dist files

### ISSUE THREAD

**Issue by Seb33300** [mladenplavsic/bootstrap-navbar-sidebar#13]
I think something is wrong with gulp when generating dist files.

In [navbar-fixed-left.css](https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/master/dist/navbar-fixed-left.css) we can find classes related to `navbar-fixed-right`.

And in [navbar-fixed-right.css](https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/master/dist/navbar-fixed-right.css), classes related to `navbar-fixed-left`.

**Comment by mladenplavsic** [comment]
Useless classes are not available anymore, closing this ticket. Changes are related to `bootstrap-v3` branch:
https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/bootstrap-v3/dist/navbar-fixed-left.css
https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/bootstrap-v3/dist/navbar-fixed-right.css
