### ISSUE TITLE
Responsive behavior

### ISSUE THREAD

**Issue by zmrenwu** [mladenplavsic/bootstrap-navbar-sidebar#14]
When in mobile settings, sidebar fails to display.

**Comment by mladenplavsic** [comment]
Yes, that's because this was intended to add sidebar behavior only for screens `>=@screen-sm-min`. I think there is no need to build it for the mobile, as default version is quite stable. What do you think?

**Comment by holtkamp** [comment]
@mladenplavsic nice plugin!

>think there is no need to build it for the mobile

Well, a use case might be to use a sidebar for a "shoppingcart" on a mobile device. By clicking a "shoppingcart" icon (collapsed NavBar), the sidebar gets activated and the user can see the content of his Order... When I got time I can come up with an example for this...

**Comment by mladenplavsic** [comment]
This is then a unique feature, which would extend the options of this simple library - which offers positioning of Bootstrap's default navbar. Let's keep it simple!
