### ISSUE TITLE
Bootstrap 4 Support?

### ISSUE THREAD

**Issue by jackttcoms** [mladenplavsic/bootstrap-navbar-sidebar#15]
Does this properly support bootstrap 4? Thanks

**Comment by cSarcasme** [comment]
apparently not

**Comment by mladenplavsic** [comment]
There is a WIP in a branch `bootstrap-v4`. Feel free to send your updates and fixes there.

**Comment by mladenplavsic** [comment]
Bootstrap v4 is now supported in `master` branch. `bootstrap-v3` branch is dedicated for Bootstrap v3.

**Comment by jackttcoms** [comment]
Thanks appreciate it 👍 🥇
