### ISSUE TITLE
Different breakpoint for right sidebar

### ISSUE THREAD

**Issue by kstadler** [mladenplavsic/bootstrap-navbar-sidebar#18]
I'm using left and right sidebar at the same time.
Would it be possible to add a feature to set a different breakpoint for the right sidebar?
That way you could display the left sidebar up to md and the right one only up to sm.

**Comment by mladenplavsic** [comment]
Hi,

I guess this is a special use case, and adding it as a feature is not something that I have on my todo list. Do you have an idea how to solve it? Using `env` variables would be such an elegant solution, but browser support is not so good :( https://caniuse.com/#feat=css-env-function

For sure there is a way to manage this by your own, changing the variables which are defined here https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/master/src/_variables.scss and applying them where needed. Let me know if I can help!

**Comment by kstadler** [comment]
As a workaround I copied the final css file from the node module into my own assets folder and changed the breakpoint manually.
Thats pretty much the best I can come up with, since I don't know very much about modern css features and scss.

**Comment by mladenplavsic** [comment]
If you don't plan to change it further, this solution is OK. Even if you used modern CSS, at the end it would generate something just like that :-)
