### ISSUE TITLE
container-fluid padding

### ISSUE THREAD

**Issue by Seb33300** [mladenplavsic/bootstrap-navbar-sidebar#2]
Hi,

Using your code with `.container-fluid` render padding in the sidebar.

Your HTML markup use `div.container` instead of `div.container-fluid` used on [bootstrap examples](https://getbootstrap.com/docs/3.3/components/#navbar-default).

Maybe you should also apply style to both `.container` & `.container-fluid` classes?

Thanks for your job.

**Comment by mladenplavsic** [comment]
Hey there!

Thanks for pointing this out, but I see that they are using `.container` in their "fixed" versions https://getbootstrap.com/docs/3.3/components/#navbar-fixed-top

Do you think we should still add support for `.container-fluid`?

**Comment by Seb33300** [comment]
`.container` class is for boxed content inside the page.
`.container-fluid` is for full width content.

You can see the difference on your demo page by replacing `.container` by `.container-fluid` on the fixed top example.
This could only be usefull for people allowing to change menu bar position like in your demo page.
