### ISSUE TITLE
when will support jquery-3.4.1 ?

### ISSUE THREAD

**Issue by gsmdenis** [mladenplavsic/bootstrap-navbar-sidebar#20]
when will support jquery-3.4.1 ?

**Comment by mladenplavsic** [comment]
I don't see any problem why jQuery cannot be upgraded. Actually, I've just bumped jQuery on demo page to `3.4.1`, check https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/master/docs/index.html#L15

**Comment by gsmdenis** [comment]
great job !
