### ISSUE TITLE
200vh min-height on body

### ISSUE THREAD

**Issue by Seb33300** [mladenplavsic/bootstrap-navbar-sidebar#7]
I don't know why, but a 200vh min-height is applied on body:
https://github.com/mladenplavsic/bootstrap-navbar-sidebar/blob/master/src/_navbar-fixed.less#L5

I think this should be removed or at least replaced by a 100% min-height.

I can create a pull request for this, what do you prefer?

**Comment by mladenplavsic** [comment]
This is here for demo purposes, and should be excluded from the source.
It would be great if you could send a PR moving this code from `src/` to `docs/docs.css`.
Thanks!
