### ISSUE TITLE
Clear navbar-collapse

### ISSUE THREAD

**Issue by Seb33300** [mladenplavsic/bootstrap-navbar-sidebar#8]
navbar-collapse should be cleared so the container will not overflow on the navbar brand

Related to: https://github.com/mladenplavsic/bootstrap-navbar-sidebar/pull/4

![image](https://user-images.githubusercontent.com/915273/35147329-7ec29f66-fd0e-11e7-9f06-2902fd1b4e64.png)

**Comment by mladenplavsic** [comment]
Hey, but what if we cancel the float of `navbar-header` with `float: none!important`? 

It was weird to me to clear floats of a non-floated element, and then I realized that `navbar-header` is floated

**Comment by Seb33300** [comment]
Yeah, disabling floating on `navbar-header` seems to be a better solution.
